# Generated by Django 2.2.12 on 2020-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoAso', models.TextField(max_length=2000, null=True)),
                ('centroF', models.ImageField(upload_to='static/img')),
                ('textoAsociacion', models.TextField(max_length=2000, null=True)),
                ('fotop', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textinicio', models.TextField(max_length=2000, null=True)),
                ('imagenInicio', models.ImageField(upload_to='static/img')),
                ('textoinicio', models.TextField(max_length=2000, null=True)),
                ('fotoinicio', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
