# Generated by Django 2.2.12 on 2020-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200610_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociacion',
            name='textoAsociacion',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
