# Generated by Django 2.2.12 on 2020-06-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
