# Generated by Django 2.2.12 on 2020-06-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200610_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['titulo']},
        ),
    ]
