# Generated by Django 2.2.12 on 2020-06-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200610_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='textinicio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='textoinicio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
