# Generated by Django 2.2.12 on 2020-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200612_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
