# Generated by Django 2.2.12 on 2020-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_inicio_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='videofile',
            field=models.FileField(default=1, upload_to='videos/', verbose_name=''),
            preserve_default=False,
        ),
    ]
