# Generated by Django 2.2.12 on 2020-06-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200622_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
