# Generated by Django 2.2.12 on 2020-06-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociacion',
            name='destacados',
            field=models.BooleanField(default=False),
        ),
    ]
