# Generated by Django 2.2.13 on 2020-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_asociacion_destacados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociacion',
            name='destacados',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='destacados',
            field=models.BooleanField(default=False),
        ),
    ]
