# Generated by Django 2.2.13 on 2020-06-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
