# Generated by Django 2.0 on 2020-06-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_video_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticias', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='destacados',
        ),
    ]
