# Generated by Django 2.0 on 2020-06-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200622_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=80, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('horario', models.CharField(max_length=80, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('estatutos', models.CharField(max_length=80, null=True)),
                ('aviso', models.CharField(max_length=80, null=True)),
                ('cookies', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
