# Generated by Django 2.0 on 2020-06-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_datoscontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontacto',
            name='aviso',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='datoscontacto',
            name='cookies',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='datoscontacto',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datoscontacto',
            name='estatutos',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
