# Generated by Django 3.0 on 2020-06-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200622_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descripcion', models.TextField(null=True)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('destacados', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
