# Generated by Django 3.0 on 2020-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200626_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filosofia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.TextField(blank=True, max_length=2000, null=True)),
                ('vision', models.TextField(blank=True, max_length=2000, null=True)),
                ('valores', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
