# Generated by Django 3.0 on 2020-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_filosofia'),
    ]

    operations = [
        migrations.AddField(
            model_name='filosofia',
            name='filosofiaasociacion',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='filosofia',
            name='titulomision',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='filosofia',
            name='titulovalores',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='filosofia',
            name='titulovision',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
