# Generated by Django 3.0 on 2020-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200626_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filosofia',
            name='filosofiaasociacion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
