# Generated by Django 3.0 on 2020-07-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200626_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='textinicio',
            new_name='iframe1',
        ),
        migrations.RenameField(
            model_name='inicio',
            old_name='textoinicio',
            new_name='iframe2',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='fotoinicio',
        ),
        migrations.AddField(
            model_name='inicio',
            name='iframe3',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='inicio',
            name='iframe4',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='inicio',
            name='youtube',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='filosofia',
            name='mision',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='filosofia',
            name='vision',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
