# Generated by Django 3.0 on 2020-07-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_tallere'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tallere',
            new_name='Talleres',
        ),
    ]
