# Generated by Django 3.0.5 on 2020-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200704_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tallere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, max_length=50000, null=True)),
                ('taller', models.TextField(blank=True, max_length=50000, null=True)),
                ('imagentaller', models.ImageField(blank=True, upload_to='static/img')),
            ],
        ),
        migrations.DeleteModel(
            name='Talleres',
        ),
    ]
