# Generated by Django 3.0.5 on 2020-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200704_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tallere',
            old_name='imagentaller',
            new_name='imagentalleres',
        ),
        migrations.AlterField(
            model_name='tallere',
            name='taller',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tallere',
            name='titulo',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
