# Generated by Django 3.0.5 on 2020-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200704_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradablog',
            name='destacados',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='fecha',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='titulo',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
