# Generated by Django 3.0.5 on 2020-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200705_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
