# Generated by Django 3.0.5 on 2020-07-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200705_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tallere',
        ),
    ]
