# Generated by Django 3.0.5 on 2020-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_tallere'),
    ]

    operations = [
        migrations.AddField(
            model_name='filosofia',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
